#
# Module manifest for module 'Invoke-DeObfuscation'
#
# Generated by: chaihj15
#
# Generated on: 2021/1/14
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ''
    
    # Version number of this module.
    ModuleVersion = '0.0.1'
    
    # Supported PSEditions
    # CompatiblePSEditions = @()
    
    # ID used to uniquely identify this module
    GUID = '5705279f-36a2-4001-ad2f-e8307257ed7c'
    
    # Author of this module
    Author = 'chaihj15'
    
    # Company or vendor of this module
    CompanyName = 'snowroll.top'
    
    # Copyright statement for this module
    Copyright = '(c) chaihj15. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'PowerShell module file for importing all required modules for the Invoke-DeObfuscation framework.'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '3.0'
    
    # Minimum version of the PowerShell host required by this module
    PowerShellHostVersion = '3.0'
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @('Utils.ps1', 'ResolveTokens.ps1', 'RenameVariables.ps1', 'Beautifier.ps1', 'InvokeDeob.ps1')
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @("./PowerShell-Beautifier")
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = "*"
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
    }
    
    